import React, { useState } from 'react';
import {
    PieChart,
    Pie,
    Cell,
    BarChart,
    Bar,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer,
    Legend
} from 'recharts';
import { FileText, ArrowRight, Filter, Download } from 'lucide-react';
import Card from '../../ui/Card';
import Button from '../../ui/Button';

const ReportsAnalytics = () => {
    // 1.1 Event Types Distribution Data
    const eventTypeData = [
        { name: 'Wedding', value: 45 },
        { name: 'Corporate', value: 25 },
        { name: 'Birthday', value: 15 },
        { name: 'Social', value: 10 },
        { name: 'Other', value: 5 },
    ];

    const PIE_COLORS = ['#f97316', '#fb923c', '#fdba74', '#fed7aa', '#ffedd5'];

    // 1.2 Booking Trends Data (Jan-Jun)
    const bookingTrendsData = [
        { name: 'Jan', bookings: 12 },
        { name: 'Feb', bookings: 18 },
        { name: 'Mar', bookings: 22 },
        { name: 'Apr', bookings: 28 },
        { name: 'May', bookings: 32 },
        { name: 'Jun', bookings: 25 },
    ];

    // 2.1 Report Cards Data
    const availableReports = [
        {
            id: 1,
            title: 'Booking based on period',
            description: 'Generate a report for bookings within a specific date range.',
            icon: FileText,
        },
        {
            id: 2,
            title: 'Booking based on package',
            description: 'Analyze booking performance by different packages.',
            icon: PackageIcon,
        },
        {
            id: 3,
            title: 'Booking based on Hall',
            description: 'View occupancy and revenue generated by each hall.',
            icon: WarehouseIcon,
        },
        {
            id: 4,
            title: 'Booking based on Event',
            description: 'Breakdown of bookings by event type and category.',
            icon: CalendarIcon,
        },
    ];

    return (
        <div className="reportsAnalyticsContainer space-y-8">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">Reports & Analytics</h1>
                    <p className="text-sm text-gray-500">Track performance metrics and generate detailed reports.</p>
                </div>

            </div>

            {/* 1. Analytics Overview Section */}
            <h2 className="text-xl font-bold text-gray-800 mb-4">Analytics Overview</h2>
            <div className="analyticsChartGrid grid grid-cols-1 lg:grid-cols-2 gap-6">

                {/* 1.1 Event Types Distribution */}
                <div className="pieChartContainer bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                    <div className="flex justify-between items-center mb-6">
                        <h3 className="text-lg font-bold text-gray-800">Event Types Distribution</h3>
                        <button className="text-[#f97316] text-sm font-medium hover:underline">View Details</button>
                    </div>
                    <div className="h-64 w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <PieChart>
                                <Pie
                                    data={eventTypeData}
                                    cx="50%"
                                    cy="50%"
                                    innerRadius={60}
                                    outerRadius={80}
                                    paddingAngle={5}
                                    dataKey="value"
                                >
                                    {eventTypeData.map((entry, index) => (
                                        <Cell key={`cell-${index}`} fill={PIE_COLORS[index % PIE_COLORS.length]} />
                                    ))}
                                </Pie>
                                <Tooltip
                                    contentStyle={{ backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e5e7eb' }}
                                />
                                <Legend
                                    layout="vertical"
                                    verticalAlign="middle"
                                    align="right"
                                    iconType="circle"
                                />
                            </PieChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* 1.2 Booking Trends */}
                <div className="barChartContainer bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                    <div className="flex justify-between items-center mb-6">
                        <h3 className="text-lg font-bold text-gray-800">Booking Trends</h3>
                        <button className="text-[#f97316] text-sm font-medium hover:underline">View Details</button>
                    </div>
                    <div className="h-64 w-full">
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={bookingTrendsData} margin={{ top: 10, right: 30, left: 0, bottom: 0 }}>
                                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5e7eb" />
                                <XAxis
                                    dataKey="name"
                                    axisLine={false}
                                    tickLine={false}
                                    tick={{ fill: '#6b7280', fontSize: 12 }}
                                    dy={10}
                                />
                                <YAxis
                                    axisLine={false}
                                    tickLine={false}
                                    tick={{ fill: '#6b7280', fontSize: 12 }}
                                    domain={[0, 35]} // Slightly above max value of 32 for padding
                                />
                                <Tooltip
                                    cursor={{ fill: '#f9fafb' }}
                                    contentStyle={{ backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e5e7eb', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}
                                />
                                <Bar
                                    dataKey="bookings"
                                    fill="#f97316"
                                    radius={[4, 4, 0, 0]}
                                    barSize={32}
                                />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>

            {/* 2. Available Reports Section */}
            <div className="reportsListSection space-y-4">
                <div className="flex justify-between items-center">
                    <h2 className="text-xl font-bold text-gray-800">Available Reports</h2>
                    <Button variant="secondary" size="sm" className="flex items-center gap-2">
                        <Filter size={16} />
                        Filter Reports
                    </Button>
                </div>

                <div className="reportCardContainer grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {availableReports.map((report) => (
                        <div key={report.id} className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 hover:shadow-md transition-shadow">
                            <div className="flex items-start justify-between mb-4">
                                <div className="p-3 bg-[#fff5f5] rounded-lg">
                                    <report.icon size={24} className="text-[#f97316]" />
                                </div>
                                <span className="px-2.5 py-1 bg-gray-100 text-gray-600 text-xs font-medium rounded-full">
                                    PDF
                                </span>
                            </div>
                            <h3 className="text-lg font-bold text-gray-900 mb-2">{report.title}</h3>
                            <p className="text-sm text-gray-500 mb-6 h-10">{report.description}</p>

                            <button className="generateReportBtn w-full flex items-center justify-between px-4 py-2 bg-gray-50 text-gray-700 font-medium rounded-lg hover:bg-gray-100 transition-colors group border border-gray-200">
                                <span>Generate</span>
                                <ArrowRight size={16} className="text-gray-400 group-hover:text-[#f97316] transition-colors" />
                            </button>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

// Helper components for icons that might not be in the direct lucide-react import
// In a real app, you'd import these from lucide-react directly
const PackageIcon = ({ size, className }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className={className}
    >
        <path d="M16.5 9.4 7.55 4.24" />
        <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
        <polyline points="3.29 7 12 12 20.71 7" />
        <line x1="12" x2="12" y1="22" y2="12" />
    </svg>
);

const WarehouseIcon = ({ size, className }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className={className}
    >
        <path d="M22 8.35V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8.35A2 2 0 0 1 3.26 6.5l8-3.2a2 2 0 0 1 1.48 0l8 3.2A2 2 0 0 1 22 8.35Z" />
        <path d="M6 18h12" />
        <path d="M6 14h12" />
        <rect width="12" height="12" x="6" y="10" />
    </svg>
);

const CalendarIcon = ({ size, className }) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        className={className}
    >
        <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
        <line x1="16" x2="16" y1="2" y2="6" />
        <line x1="8" x2="8" y1="2" y2="6" />
        <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
);

export default ReportsAnalytics;
